use sample
CREATE TABLE Employee4
(
  Id int Primary Key,
  Name nvarchar(30),
  Salary int,
  Gender nvarchar(10),
  DepartmentId int
)
INSERT INTO Employee4 VALUES (1,'Pranaya', 5000, 'Male', 3)
INSERT INTO Employee4 VALUES (2,'Priyanka', 5400, 'Female', 2)
INSERT INTO Employee4 VALUES (3,'Anurag', 6500, 'male', 1)
INSERT INTO Employee4 VALUES (4,'sambit', 4700, 'Male', 2)
INSERT INTO Employee4 VALUES (5,'Hina', 6600, 'Female', 3)
select * from Employee4
CREATE TRIGGER trinsertEmployee4 
ON Employee4
FOR INSERT
AS
BEGIN
  PRINT 'YOU CANNOT PERFORM INSERT OPERATION'
  ROLLBACK TRANSACTION
END
INSERT INTO Employee4 VALUES (6, 'Saroj', 7600, 'Male', 1)

CREATE TRIGGER trupdate1Employee4 
ON Employee4
FOR UPDATE
AS
BEGIn
  PRINT 'YOU CANNOT PERFORM UPDATE OPERATION'
  ROLLBACK TRANSACTION
END
UPDATE Employee4 SET Salary = 90000 WHERE Id = 1
select * from Employee4

CREATE TRIGGER trDeleteEmployee4 
ON Employee4
FOR DELETE
AS
BEGIN
  PRINT 'YOU CANNOT PERFORM DELETE OPERATION'
  ROLLBACK TRANSACTION
END
DELETE FROM Employee4 WHERE Id = 1

DROP TRIGGER trDeleteEmployee4
DROP TRIGGER trInsertEmployee4
DROP TRIGGER trUpdate1Employee4

CREATE TRIGGER trAllDMLOperationsOnEmployee4 
ON Employee
FOR INSERT, UPDATE, DELETE
AS
BEGIN
  PRINT 'YOU CANNOT PERFORM DML OPERATION'
  ROLLBACK TRANSACTION
END
ALTER TRIGGER trAllDMLOperations OnEmployee4
ON Employee4
FOR INSERT, UPDATE, DELETE
AS
BEGIN
  IF DATEPART(DW,GETDATE())= 2
  BEGIN
    PRINT 'DML OPERATIONS ARE RESTRICTED ON MONDAY'
    ROLLBACK TRANSACTION
  END
END

CREATE TRIGGER trInsertEmployee4 
ON Employee4
FOR INSERT
AS
BEGIN
  SELECT * FROM INSERTED
END
INSERT INTO Employee4 VALUES (6, 'Saroj', 7700, 'Male', 2)

CREATE TRIGGER trDeleteEmployee4 
ON Employee4
FOR DELETE
AS
BEGIN
  SELECT * FROM DELETED
END
DELETE FROM Employee4 WHERE Id = 6

CREATE TRIGGER trUpdate1Employee4
ON Employee4
FOR UPDATE
AS
BEGIN
  SELECT * FROM DELETED
  SELECT * FROM INSERTED
END
UPDATE Employee4 SET Name = 'Sharma', Salary = 8000 WHERE Id = 5

CREATE TABLE Department1
(
  ID INT PRIMARY KEY,
  Name VARCHAR(50)
)
INSERT INTO Department1 VALUES(1, 'IT')
INSERT INTO Department1 VALUES(2, 'HR')
INSERT INTO Department1 VALUES(3, 'Sales')

CREATE TABLE Employee5
(
  ID INT PRIMARY KEY,
  Name VARCHAR(50),
  Gender VARCHAR(50),
  DOB DATETIME,
  Salary DECIMAL(18,2),
  DeptID INT
)
INSERT INTO Employee5 VALUES(1, 'Pranaya', 'Male','1996-02-29 10:53:27.060', 25000, 1)
INSERT INTO Employee5 VALUES(2, 'Priyanka', 'Female','1995-05-25 10:53:27.060', 30000, 2)
INSERT INTO Employee5 VALUES(3, 'Anurag', 'Male','1995-04-19 10:53:27.060',40000, 2)
INSERT INTO Employee5 VALUES(4, 'Preety', 'Female','1996-03-17 10:53:27.060', 35000, 3)
INSERT INTO Employee5 VALUES(5, 'Sambit', 'Male','1997-01-15 10:53:27.060', 27000, 1)
INSERT INTO Employee5 VALUES(6, 'Hina', 'Female','1995-07-12 10:53:27.060', 33000, 2)
select * from employee5
 create database MyDemo
USE MyDemo
GO

CREATE  TRIGGER  trRestrictCreateTable 
ON DATABASE
FOR CREATE_TABLE
AS
BEGIN
  PRINT 'YOU CANNOT CREATE A TABLE IN THIS DATABASE'
  ROLLBACK TRANSACTION
END
CREATE TABLE tblTest (ID INT)

CREATE TRIGGER  trRestrictAlterTable  
ON DATABASE
FOR  ALTER_TABLE
AS
BEGIN
  PRINT 'YOU CANNOT ALTER TABLES'
  ROLLBACK TRANSACTION
END
DROP TRIGGER trRestrictCreateTable ON DATABASE
DROP TRIGGER trRestrictAlterTable ON DATABASE

CREATE TRIGGER trRestrictDDLEvents
ON DATABASE
FOR CREATE_TABLE, ALTER_TABLE, DROP_TABLE
AS
BEGIN 
   PRINT 'You cannot create, alter or drop a table'
   ROLLBACK TRANSACTION
END

CREATE TRIGGER trServerScopedDDLTrigger
ON ALL SERVER
FOR CREATE_TABLE, ALTER_TABLE, DROP_TABLE
AS
BEGIN 
   PRINT 'You cannot create, alter or drop a table in any database of this server'
   ROLLBACK TRANSACTION
END

